### ISSUE TITLE
Batter_state topic publishes incorrect current value

### ISSUE THREAD

**Issue by ipa-rar** [turtlebot/turtlebot4_robot#15]
**Please provide the following information:**
 - OS: (e.g. Ubuntu 20.04)
 - ROS Distro: (e.g. Galactic)
 - installed:

 **Expected behaviour**
A positive value for current value when the robot is on or moving

 **Actual behaviour**
A negative value of current and it does change over time

````
---
header:
  stamp:
    sec: 1678881679
    nanosec: 300413300
  frame_id: ''
voltage: 16.090999603271484
temperature: 33.14999771118164
**current: -0.7149999737739563**   #Negative current value
charge: 1.940000057220459
capacity: 2.046999931335449
design_capacity: 2.046999931335449
percentage: 0.949999988079071
power_supply_status: 0
power_supply_health: 0
power_supply_technology: 0
present: true
cell_voltage: []
cell_temperature: []
location: ''
serial_number: ''
---
````

**To Reproduce**
Provide the steps to reproduce:
1.  `ros2 run teleop_twist_keyboard teleop_twist_keyboard `
2. `ros2 topic echo /battery_state`
